AWSTemplateFormatVersion: '2010-09-09'
Description: Amazon MACIE CloudFormation script for member accounts.

Parameters:
  MasterAccount:
      Description: "Account number of the master Amazon Macie account to grant access to"
      Type: String
      AllowedPattern: "[0-9]*"
      MinLength: 11
      MaxLength: 12
      ConstraintDescription: "Must be a 12 digit AWS Account Number"

Resources:
  AWSMacieServiceCustomerHandshakeRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AWSMacieServiceCustomerHandshakeRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - "macie.amazonaws.com"
          Action:
          - sts:AssumeRole
          Condition:
            StringEquals:
              "sts:ExternalId": 
              - Ref : MasterAccount
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonMacieHandshakeRole